### ISSUE TITLE
Hashed string isn't the same as if I'm testing hashing with online tools

### ISSUE THREAD

**Issue by bosstjan** [Nerolation/GTM-UserID-Hash-To-Cookie#1]
Hi, when using this tag template the tag doesn't return the same hash as if I'm testing hashing with online tools.

Example with this tag template:
- string to hash: testingABCDE
- hashed string without base64: GgGMWg4d8Gn5JQjjCW+4WbCgtyB+etN8leHQcIFuOPs=
- hashed string with base64: R2dHTVdnNGQ4R241SlFqakNXKzRXYkNndHlCK2V0TjhsZUhRY0lGdU9Qcz
- hashed string with online tools (i.e. emn178.github.io/online-tools/sha256.html, md5calc.com/hash/sha256/testingABCDE): 1a018c5a0e1df069f92508e3096fb859b0a0b7207e7ad37c95e1d070816e38fb

Is this a bug or the way it works? Why are the values different?

**Comment by nerolation** [comment]
Tbh, it's quite some time since I wrote that tag.
You'd probably have to check the google docs on how the hashing works exactly. I don't remember if it involved a random salt or had some prefix anymore.. but maybe. 
Also, depending on how it's encoded (string, hex, bytes) etc could make a difference and I'm not sure how google comes up with it.

**Comment by bosstjan** [comment]
Hey, I understand what you're saying.

If you plan to update the code, here's the article that describes the solution by using the Cloudflare's CryptoJS library. I tested it and it returns the values I'm expecting: www.linkedin.com/pulse/how-protect-sensitive-user-data-sha-256-hashing-cryptojs-manish-k-b/.

I haven't checked with Google's docs if the hashed value is ok, but I think it's the first step at least.
